### ISSUE TITLE
does not parse dash?

### ISSUE THREAD

**Issue by rheilgm** [RyanMarcus/dirty-json#14]
![image](https://user-images.githubusercontent.com/7484661/42547503-1061b920-84f5-11e8-8236-b01b4e277527.png)

for some reason it converts dashes to `NaN` when its inside the quotes

**Comment by RyanMarcus** [comment]
Oh, that's a fun one! I'm guessing the bug is in this line of lexer.js:

`lexer.addRule(/[\-0-9]+/, lexeme => {`

... because it will accept "-"... the correct regex is probably `\-?[0-9]+`.

Unfortunately, I'm working for Google right now, and their lawyer's claim any code I write this summer becomes Google's property. I'll have to fix this when I return to school in August.

**Comment by RyanMarcus** [comment]
I believe I've fixed the bug. Will do a release soon.

**Comment by RyanMarcus** [comment]
Fixed in `0.7.0`. The online demo should be update to date soon.
